### PR TITLE
db backup mgmt

### PR DESCRIPTION
**Pull request by neurosnap**
https://github.com/aptible/app-ui/assets/1940365/e243dbf7-6ae1-45a0-bb54-67d2eb18241d

https://github.com/aptible/app-ui/assets/1940365/c91f80ee-b21c-471b-b33f-42c30bffb05b

### CODE REVIEW

**Comment by madhuravius** [comment]
nit but the vertical scrolling on tables is a bit weird (what i saw in the video). i know it's not scope of PR but just pointing it out

**Review by madhuravius — APPROVED** [review]
LGTM for create, did you plan on adding that delete one as well?

image

or is that something we're prob gonna come back to later with more full stack changes

**Comment by joeclayallday** [comment]
Screen Shot 2023-08-07 at 1 07 38 PM

Screen Shot 2023-08-07 at 1 07 43 PM

**Comment by joeclayallday** [comment]
Style Tweaks
Screen Shot 2023-08-07 at 1 28 39 PM

Screen Shot 2023-08-07 at 1 29 50 PM

**Review by madhuravius — APPROVED** [review]

**Pull request merged**
