### PR TITLE
chore(ftux): mark onboarding_status based on start instead of success

### PR DESCRIPTION
**Pull request by neurosnap**

### CODE REVIEW

**Review by madhuravius — COMMENTED** [review]
do we want to add backend statuses or changes as a result of this?

**Comment by neurosnap** [comment]
I honestly don't think it's necessary, but I'll defer to your judgement

**Comment by madhuravius** [comment]
the only reason i was asking was because this won't work unless it fits certain statuses.

if this works fine against backend we're g2g, i think a simple pass with you is enough for approval

**Comment by neurosnap** [comment]
#63 supersedes

**Pull request closed without merging**
