### PR TITLE
Feat: Hosting options page

### PR DESCRIPTION
**Pull request by joshraker**
TODO:

- [X] Hover style
- [X] Waitlist banner
- [x] Fix tests

### CODE REVIEW

**Comment by joshraker** [comment]
https://app.shortcut.com/aptible/story/22716/prototype-add-a-self-hosted-option-to-the-signup-experience

**Comment by joshraker** [comment]
https://app.shortcut.com/aptible/story/22719/prototype-measure-intent-and-falloff-for-self-hosted-signup

**Comment by joshraker** [comment]
Banner + hover styling

Screenshot 2024-03-22 at 13 01 23

**Review by joeclayallday — APPROVED** [review]

**Review by grrowe — APPROVED** [review]
lgtm!

**Pull request merged**
